"""Grader-invariance analysis of D = C*a_n on the Tevet conTest datasets.

Question: is the metric a property of the text being scored, or of the grader
theta scoring it? For each conTest file (prompt_gen / resp_gen / story_gen)
and each grader run tag, per-sample D = C * a_n (per byte; the paper's primary
metric, derived exactly as in analyze_c_ainf.py, mean-of-ratios over the
per-permutation curves) is computed from the full .icl_curves sidecars, then:

  1. Per-grader Spearman rho between D and the human diversity label
     (label_value), on the common sample subset: does every grader see the
     signal the paper's grader sees?
  2. Pairwise Spearman between graders' per-sample D: do different-family,
     different-scale graders rank the same texts the same way?
  3. Two-way variance decomposition of the (item x grader) D matrix, raw and
     within-grader z-scored. Raw grader share includes each grader's absolute
     scale offset (GPT-2 is not on the same bits/byte scale as a 30B model);
     the z-scored view removes scale and location, leaving item share vs
     grader x item disagreement.

Sidecar discovery: each tag's conTest sidecars are searched first under this
repo's results/tevet/<tag>/, then under the main checkout's results/tevet/<tag>/
(the pre-existing qwen25_completion_v3 and qwen3_30b_a3b runs live there as
gitignored artifacts). The path used is recorded in the output JSON.

Outputs (results/tevet/grader_invariance/):
  invariance.json               full numbers
  generated_tables.md           markdown tables (spliced into FINDINGS.md)
  tevet_invariance_rho.tex      LaTeX table body for the paper
  tevet_invariance_macros.tex   \\newcommand macros for inline prose numbers

Usage:
  uv run python scripts/analyze_tevet_grader_invariance.py
  uv run python scripts/analyze_tevet_grader_invariance.py --tags qwen25_completion_v3 gpt2_completion
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path

import numpy as np
from scipy import stats

REPO_ROOT = Path(__file__).resolve().parents[1]
SEARCH_ROOTS = [
    REPO_ROOT / "results" / "tevet",
    Path("/home/cs29824/matthew/icl-diversity/results/tevet"),
]
OUT_DIR = REPO_ROOT / "results" / "tevet" / "grader_invariance"

# (run tag, display name, macro fragment)
TAG_SPECS = [
    ("qwen25_completion_v3", "Qwen2.5-3B", "Qwen"),
    ("qwen3_30b_a3b", "Qwen3-30B-A3B", "QwenMoe"),
    ("llama8b_completion", "Llama-3.1-8B", "Llama"),
    ("gpt2_completion", "GPT-2 124M", "GptTwo"),
]

# (csv stem, display name, macro fragment)
FILE_SPECS = [
    ("con_test_200_with_hds_prompt_gen", "prompt\\_gen", "PromptGen"),
    ("con_test_200_with_hds_resp_gen", "resp\\_gen", "RespGen"),
    ("con_test_200_with_hds_story_gen", "story\\_gen", "StoryGen"),
]

GENERATED_BY = "Auto-generated by scripts/analyze_tevet_grader_invariance.py -- do not hand-edit."


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


CAI = _load_module(REPO_ROOT / "scripts" / "analyze_c_ainf.py", "c_ainf_mod")
MPO = _load_module(
    REPO_ROOT / "scripts" / "rlhf_experiment" / "7_matrix_paper_outputs.py",
    "matrix_paper_outputs_mod",
)


def find_tag_dir(tag: str) -> Path:
    for root in SEARCH_ROOTS:
        cand = root / tag / "conTest"
        if cand.exists() and any(cand.glob(f"*.icl_curves.{tag}.json")):
            return cand
    raise FileNotFoundError(
        f"no conTest .icl_curves.{tag}.json sidecars found for tag {tag!r} under "
        f"{[str(r) for r in SEARCH_ROOTS]}"
    )


def load_tag_file(tag: str, tag_dir: Path, stem: str) -> dict[str, dict]:
    """{sidecar_key: {'D': C*a_n per byte, 'label': float}} for one CSV file."""
    sidecar_path = tag_dir / f"{stem}.icl_curves.{tag}.json"
    csv_path = tag_dir / f"{stem}.csv"
    if not sidecar_path.exists():
        raise FileNotFoundError(sidecar_path)
    if not csv_path.exists():
        raise FileNotFoundError(csv_path)
    sidecar = CAI.load_sidecar(sidecar_path)
    csv_rows = CAI.load_csv_rows(csv_path)
    out: dict[str, dict] = {}
    for key, entry in sidecar.items():
        row = csv_rows.get(key)
        if row is None:
            continue
        label = float(row["label_value"])
        m = CAI.compute_sample_metrics(entry, label, tag, row, skip_fit=True)
        if m is None:
            raise ValueError(
                f"tag={tag} file={stem} sample={key}: sample metrics could not be "
                "computed (degenerate sidecar entry); refusing to silently drop it"
            )
        out[key] = {"D": float(m["C_a_n_pb"]), "label": label}
    if not out:
        raise ValueError(f"tag={tag} file={stem}: no samples loaded")
    return out


def zscore_columns(M: np.ndarray) -> np.ndarray:
    mean = M.mean(axis=0, keepdims=True)
    sd = M.std(axis=0, ddof=1, keepdims=True)
    if np.any(sd == 0):
        raise ValueError("degenerate grader column with zero variance")
    return (M - mean) / sd


def analyze_file(per_tag: dict[str, dict[str, dict]], tags: list[str]) -> dict:
    key_sets = {t: set(per_tag[t]) for t in tags}
    common = sorted(set.intersection(*key_sets.values()))
    if len(common) < 30:
        raise ValueError(f"only {len(common)} common samples across tags; too few")
    labels = np.array([per_tag[tags[0]][k]["label"] for k in common])
    # Labels must agree across tags (same underlying CSV rows).
    for t in tags[1:]:
        other = np.array([per_tag[t][k]["label"] for k in common])
        if not np.allclose(labels, other):
            raise AssertionError(f"label mismatch between {tags[0]} and {t}")

    D = np.column_stack([[per_tag[t][k]["D"] for k in common] for t in tags])

    rho_label = {}
    for j, t in enumerate(tags):
        rho, p = stats.spearmanr(D[:, j], labels)
        rho_label[t] = {"rho": float(rho), "p": float(p)}

    pairwise = {}
    for i, ti in enumerate(tags):
        for j in range(i + 1, len(tags)):
            rho, p = stats.spearmanr(D[:, i], D[:, j])
            pairwise[f"{ti}|{tags[j]}"] = {"rho": float(rho), "p": float(p)}

    raw = MPO.two_way_decomposition(D)
    zs = MPO.two_way_decomposition(zscore_columns(D))

    def relabel(d: dict) -> dict:
        return {
            "item": d["frac"]["row"],
            "grader": d["frac"]["col"],
            "interaction": d["frac"]["interaction"],
        }

    return {
        "n_common": len(common),
        "n_per_tag": {t: len(key_sets[t]) for t in tags},
        "rho_vs_label": rho_label,
        "pairwise_grader_rho": pairwise,
        "variance_raw_frac": relabel(raw),
        "variance_zscored_frac": relabel(zs),
        "min_pairwise_rho": min(v["rho"] for v in pairwise.values()),
        "rho_spread": max(v["rho"] for v in rho_label.values())
        - min(v["rho"] for v in rho_label.values()),
    }


def pct1(frac: float) -> str:
    return f"{100 * frac:.1f}"


def fmt2(x: float) -> str:
    return f"{x:.2f}"


def emit_tex_rho(results: dict, tags: list[str]) -> str:
    tag_disp = {t: d for t, d, _m in TAG_SPECS}
    lines = [
        "% " + GENERATED_BY,
        "\\begin{tabular}{l" + "c" * len(FILE_SPECS) + "}",
        "\\toprule",
        "$\\theta$ (grader) & " + " & ".join(d for _s, d, _m in FILE_SPECS) + " \\\\",
        "\\midrule",
    ]
    for t in tags:
        cells = [fmt2(results[stem]["rho_vs_label"][t]["rho"]) for stem, _d, _m in FILE_SPECS]
        lines.append(f"{tag_disp[t]} & " + " & ".join(cells) + " \\\\")
    lines.append("\\midrule")
    item_cells = [
        pct1(results[stem]["variance_zscored_frac"]["item"]) + "\\%" for stem, _d, _m in FILE_SPECS
    ]
    lines.append("Item share of z-scored variance & " + " & ".join(item_cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def emit_macros(results: dict, tags: list[str]) -> str:
    tag_macro = {t: m for t, _d, m in TAG_SPECS}
    lines = [
        "% " + GENERATED_BY,
        "% Inline-number macros for the Tevet grader-invariance analysis.",
    ]

    def add(name: str, value: str) -> None:
        lines.append(f"\\newcommand{{\\tevetInv{name}}}{{{value}}}")

    all_rho: list[float] = []
    all_pair: list[float] = []
    all_item: list[float] = []
    for stem, _disp, fmac in FILE_SPECS:
        r = results[stem]
        add(f"{fmac}N", str(r["n_common"]))
        for t in tags:
            add(f"{fmac}Rho{tag_macro[t]}", fmt2(r["rho_vs_label"][t]["rho"]))
            all_rho.append(r["rho_vs_label"][t]["rho"])
        add(f"{fmac}RhoSpread", fmt2(r["rho_spread"]))
        add(f"{fmac}MinPairRho", fmt2(r["min_pairwise_rho"]))
        all_pair.append(r["min_pairwise_rho"])
        add(f"{fmac}ItemPct", pct1(r["variance_zscored_frac"]["item"]))
        all_item.append(r["variance_zscored_frac"]["item"])
        add(f"{fmac}InteractPct", pct1(r["variance_zscored_frac"]["interaction"]))
        add(f"{fmac}RawGraderPct", pct1(r["variance_raw_frac"]["grader"]))
        add(f"{fmac}RawItemPct", pct1(r["variance_raw_frac"]["item"]))
    add("NGraders", str(len(tags)))
    add("MinRho", fmt2(min(all_rho)))
    add("MinPairRho", fmt2(min(all_pair)))
    add("MinItemPct", pct1(min(all_item)))
    return "\n".join(lines) + "\n"


def emit_markdown(results: dict, tags: list[str], tag_dirs: dict[str, str]) -> dict[str, str]:
    tag_disp = {t: d for t, d, _m in TAG_SPECS}
    blocks: dict[str, str] = {}

    header = "| grader θ | " + " | ".join(s.split("hds_")[1] for s, _d, _m in FILE_SPECS) + " |"
    lines = [header, "|---|" + "---|" * len(FILE_SPECS)]
    for t in tags:
        cells = [fmt2(results[stem]["rho_vs_label"][t]["rho"]) for stem, _d, _m in FILE_SPECS]
        lines.append(f"| {tag_disp[t]} | " + " | ".join(cells) + " |")
    blocks["tevet-rho-by-grader"] = "\n".join(lines)

    lines = [
        "| conTest file | n | item % (z-scored) | interaction % (z-scored) | grader % (raw) | min pairwise ρ |",
        "|---|---|---|---|---|---|",
    ]
    for stem, _d, _m in FILE_SPECS:
        r = results[stem]
        lines.append(
            f"| {stem.split('hds_')[1]} | {r['n_common']} | "
            f"{pct1(r['variance_zscored_frac']['item'])}% | "
            f"{pct1(r['variance_zscored_frac']['interaction'])}% | "
            f"{pct1(r['variance_raw_frac']['grader'])}% | "
            f"{fmt2(r['min_pairwise_rho'])} |"
        )
    blocks["tevet-invariance-variance"] = "\n".join(lines)
    return blocks


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tags", nargs="+", default=[t for t, _d, _m in TAG_SPECS],
                    help="grader subset to analyze (default: all four TAG_SPECS tags)")
    ap.add_argument("--update-findings", action="store_true",
                    help="splice generated tables into this directory's FINDINGS.md")
    ap.add_argument(
        "--output-dir", type=Path, default=None,
        help="if set, write outputs here as <stem>.json / <stem>_generated_tables.md instead "
             "of the default results/tevet/grader_invariance/{invariance.json,"
             "generated_tables.md,tevet_invariance_rho.tex,tevet_invariance_macros.tex}. No "
             "LaTeX files are emitted in this mode (avoids collisions with the paper-facing "
             "tevet_invariance_*.tex files), and --update-findings is unavailable.",
    )
    ap.add_argument(
        "--output-stem", default="invariance",
        help="filename stem used only when --output-dir is set (default: invariance)",
    )
    args = ap.parse_args()

    known = {t for t, _d, _m in TAG_SPECS}
    unknown = set(args.tags) - known
    if unknown:
        raise SystemExit(f"unknown tags {sorted(unknown)}; known: {sorted(known)}")
    if args.output_dir is not None and args.update_findings:
        raise SystemExit(
            "--update-findings is unavailable with --output-dir (it always splices "
            f"{OUT_DIR / 'FINDINGS.md'}, which would be the wrong file for a custom output dir)"
        )

    tag_dirs = {t: find_tag_dir(t) for t in args.tags}
    results: dict[str, dict] = {}
    for stem, _disp, _mac in FILE_SPECS:
        per_tag = {t: load_tag_file(t, tag_dirs[t], stem) for t in args.tags}
        results[stem] = analyze_file(per_tag, args.tags)

    out = {
        "generated_by": "scripts/analyze_tevet_grader_invariance.py",
        "metric": "C_a_n_pb (D = C x a_n, per byte; derivation of analyze_c_ainf.py)",
        "tags": args.tags,
        "tag_dirs": {t: str(d) for t, d in tag_dirs.items()},
        "files": results,
    }
    blocks = emit_markdown(results, args.tags, {t: str(d) for t, d in tag_dirs.items()})
    md = [f"<!-- {GENERATED_BY} -->", ""]
    for name, content in blocks.items():
        md += [f"## {name}", "", content, ""]

    if args.output_dir is not None:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        (args.output_dir / f"{args.output_stem}.json").write_text(json.dumps(out, indent=2))
        (args.output_dir / f"{args.output_stem}_generated_tables.md").write_text("\n".join(md))
    else:
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        (OUT_DIR / "invariance.json").write_text(json.dumps(out, indent=2))
        (OUT_DIR / "tevet_invariance_rho.tex").write_text(emit_tex_rho(results, args.tags))
        (OUT_DIR / "tevet_invariance_macros.tex").write_text(emit_macros(results, args.tags))
        (OUT_DIR / "generated_tables.md").write_text("\n".join(md))
        if args.update_findings:
            MPO.splice_findings(OUT_DIR / "FINDINGS.md", blocks)

    for stem, _disp, _mac in FILE_SPECS:
        r = results[stem]
        rhos = " ".join(f"{t}={r['rho_vs_label'][t]['rho']:.2f}" for t in args.tags)
        print(f"[{stem}] n={r['n_common']} rho_vs_label: {rhos}")
        print(
            f"           z-scored item {100*r['variance_zscored_frac']['item']:.1f}% / "
            f"interaction {100*r['variance_zscored_frac']['interaction']:.1f}%  |  "
            f"raw grader {100*r['variance_raw_frac']['grader']:.1f}%  |  "
            f"min pairwise rho {r['min_pairwise_rho']:.2f}"
        )


if __name__ == "__main__":
    main()
