"""Diagnostic: is the canonical-vs-scrambled distinct-n gap a capitalization artifact?

In the canonical condition the sentence-initial (capitalized) word is always a
noun; in the scrambled control it is whichever word the per-sentence shuffle
puts first. Because Tevet-convention distinct-n tokenization is case-sensitive
(it strips '.' only), scrambling spreads capitalization across word classes and
case-splits more word types, slightly raising distinct-n for reasons unrelated
to word order structure.

Test: recompute averaged distinct-n on lowercased responses. If the gap
collapses, the raw-text gap is the case-splitting artifact.

Usage:
    uv run python scripts/check_scrambled_distinctn_capitalization.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from scipy.stats import ttest_ind

from icl_diversity.baseline_metrics import averaged_distinct_ngrams

REPO = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = REPO / "results" / "pos_pattern" / "qwen2.5-3b_scrambled_control.json"
DEFAULT_OUTPUT = (
    REPO
    / "figures"
    / "pos_pattern"
    / "qwen2.5-3b_scrambled_control"
    / "distinctn_case_check.txt"
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Lowercased distinct-n check for the scrambled control"
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    by_cond: dict[str, dict[str, list[float]]] = {}
    for run in data["runs"]:
        d = by_cond.setdefault(run["condition"], {"raw": [], "lowercased": []})
        d["raw"].append(averaged_distinct_ngrams(run["responses"]))
        d["lowercased"].append(
            averaged_distinct_ngrams([r.lower() for r in run["responses"]])
        )
    if set(by_cond) != {"canonical", "scrambled"}:
        raise ValueError(
            f"Expected canonical and scrambled runs, got {sorted(by_cond)}"
        )

    lines = [
        "Averaged distinct-n, canonical vs scrambled, raw vs lowercased responses",
        f"Source: {args.input}",
        "Generated by: scripts/check_scrambled_distinctn_capitalization.py",
        "",
    ]
    for variant in ["raw", "lowercased"]:
        a = np.array(by_cond["canonical"][variant])
        b = np.array(by_cond["scrambled"][variant])
        t, p = ttest_ind(a, b, equal_var=False)
        lines.append(
            f"{variant:>10s}: canonical {a.mean():.4f} ± {a.std(ddof=1):.4f}   "
            f"scrambled {b.mean():.4f} ± {b.std(ddof=1):.4f}   "
            f"diff {a.mean() - b.mean():+.4f}   t = {t:+.2f}  (p = {p:.2g})"
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWritten to: {args.output}")


if __name__ == "__main__":
    main()
