"""Check whether C × a_∞ tracks mode count in the Regime 1 experiments.

Data provenance:
- Input: results/mode_count/{gpt2,qwen2.5-3b}_1k_draws.json
- Generated by: scripts/run_mode_count_experiment.py
  - 20 responses per draw, 1000 independent draws per mode count m ∈ {1..10}
  - Each draw: fresh response generation → shuffle → compute_icl_diversity_metrics
  - n_permutations=1 because randomness comes from the shuffle + independent draws
    (see comment in run_mode_count_experiment.py lines 110-115)
  - Each run's a_k_curve is a single-ordering curve (noisy per-run)
  - C and a_n are permutation-invariant, so they are meaningful per-run

- Optional: results/mode_count/{model}_fits.json
  - Generated by: scripts/fit_ak_curves.py --save-fits
  - Fits sigmoid/exponential to the mean a_k curve (averaged across 1000 draws)
    for each m. One fit entry per m. See fit_mean_curves() in fit_ak_curves.py.

Two analysis approaches:
1. Per-m aggregate: average curves across 1000 draws for each m, fit the smooth
   mean curve, compare fitted metrics across m. This is what fit_ak_curves.py does.
2. Per-run ranking: use permutation-invariant quantities (C, a_n) per-run to
   compute Spearman ρ(metric, m) across all 10k runs.

Usage:
    uv run python scripts/check_ainf_vs_mode_count.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from scipy.stats import pearsonr, spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fit_ak_curves import fit_exponential

RESULTS_DIR = Path(__file__).resolve().parent.parent / "results" / "mode_count"


def analyze_mode_count_file(path: Path) -> None:
    """Load mode count results and compare metrics."""
    with open(path) as f:
        raw = json.load(f)

    entries = raw["runs"] if isinstance(raw, dict) and "runs" in raw else raw

    n_responses = raw.get("n_responses", "?")
    n_draws = raw.get("n_draws", "?")

    print(f"\n{'=' * 80}")
    print(f"  {path.name}")
    print(f"  Config: {n_responses} responses/draw, {n_draws} draws/m, n_permutations=1")
    print(f"{'=' * 80}")

    # Group runs by mode count
    by_m: dict[int, list[dict]] = {}
    for entry in entries:
        m = int(entry["m"])
        by_m.setdefault(m, []).append(entry)

    unique_m = sorted(by_m.keys())

    # ── Approach 1: Per-m aggregate (mean curve, then fit) ──
    print(f"\n  ── Per-m aggregate (mean curve across {n_draws} draws, then fit) ──")

    agg: dict[str, list[float]] = {
        "C×a_n": [], "C×a_inf_fit": [], "D_fit=C×E_fit": [],
        "a_n": [], "a_inf_fit": [], "E_fit": [],
        "C": [], "a_1": [],
    }

    for m in unique_m:
        runs = by_m[m]
        curves = np.array([r["a_k_curve"] for r in runs])
        mean_curve = np.mean(curves, axis=0)
        mean_C = float(np.mean([r["coherence_C"] for r in runs]))
        a_n = float(mean_curve[-1])

        k = np.arange(1, len(mean_curve) + 1, dtype=float)
        fit_params, fit_ok = fit_exponential(k, mean_curve)

        a_inf = fit_params["a_inf"] if fit_ok else a_n
        E_fit = fit_params["E_fit"] if fit_ok else 0.0

        agg["a_n"].append(a_n)
        agg["a_inf_fit"].append(a_inf)
        agg["E_fit"].append(E_fit)
        agg["C"].append(mean_C)
        agg["a_1"].append(float(mean_curve[0]))
        agg["C×a_n"].append(mean_C * a_n)
        agg["C×a_inf_fit"].append(mean_C * a_inf)
        agg["D_fit=C×E_fit"].append(mean_C * E_fit)

    mc_arr = np.array(unique_m, dtype=float)
    print(f"\n  {'Metric':<20s} {'Spearman ρ':>12s} {'Pearson r':>12s} {'Monotonic?':>12s}")
    print(f"  {'-'*20} {'-'*12} {'-'*12} {'-'*12}")
    for name, vals in agg.items():
        rho, _ = spearmanr(mc_arr, vals)
        r, _ = pearsonr(mc_arr, vals)
        diffs = np.diff(vals)
        mono = "YES" if np.all(diffs > 0) else "no"
        print(f"  {name:<20s} {rho:>+12.4f} {r:>+12.4f} {mono:>12s}")

    # Table of values
    table_keys = ["C×a_n", "C×a_inf_fit", "D_fit=C×E_fit", "a_n", "a_inf_fit", "E_fit", "C"]
    col_w = 11
    header = f"\n  {'m':>3s}" + "".join(f" {k:>{col_w}s}" for k in table_keys)
    print(header)
    print(f"  {'---':>3s}" + "".join(f" {'-'*col_w:>{col_w}s}" for _ in table_keys))
    for i, m in enumerate(unique_m):
        line = f"  {m:>3d}"
        for k in table_keys:
            line += f" {agg[k][i]:>{col_w}.3f}"
        print(line)

    # ── Approach 2: Per-run ranking (single-permutation, noisy) ──
    # Each run uses n_permutations=1, so a_n depends on which response lands
    # last — it is NOT permutation-invariant. C is permutation-invariant.
    # The per-run correlations are a noisy lower bound; with permutation
    # averaging (as in the Tevet evaluation with 50 permutations), the
    # signal would be stronger.
    print(f"\n  ── Per-run ranking (single-perm, noisy lower bound) ──")

    run_m = np.array([float(e["m"]) for e in entries])
    run_c = np.array([e["coherence_C"] for e in entries])
    run_an = np.array([e["a_k_curve"][-1] for e in entries])

    for name, vals in [
        ("C × a_n", run_c * run_an),
        ("a_n (raw)", run_an),
        ("C", run_c),
    ]:
        rho, p_rho = spearmanr(run_m, vals)
        r, p_r = pearsonr(run_m, vals)
        print(f"  {name:<20s} Spearman ρ = {rho:+.4f}, Pearson r = {r:+.4f}  (n = {len(run_m)})")


def main() -> None:
    for name in ["gpt2_1k_draws.json", "qwen2.5-3b_1k_draws.json"]:
        path = RESULTS_DIR / name
        if path.exists():
            analyze_mode_count_file(path)
        else:
            print(f"Not found: {path}")


if __name__ == "__main__":
    main()
