"""Compare per-task results between Qwen2.5-3B and Qwen3-30B-A3B-Base on Tevet.

Reads the two summary_table.txt files generated by analyze_c_ainf.py and prints
a side-by-side comparison for the C×a_n (pb) metric across all tasks/sections.
With --emit-latex, also writes a tabular body to results/tables/qwen3_comparison.tex
for inclusion in the paper appendix.

Usage:
    uv run python scripts/compare_qwen_models.py
    uv run python scripts/compare_qwen_models.py --emit-latex
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
Q3_PATH = PROJECT_ROOT / "figures/tevet_validation/c_ainf_analysis_v3/summary_table.txt"
QN_PATH = PROJECT_ROOT / "figures/tevet_validation/c_ainf_analysis_qwen3/summary_table.txt"
LATEX_OUT_PATH = PROJECT_ROOT / "results/tables/qwen3_comparison.tex"

SECTION_RE = re.compile(r"^\s+(McDiv_nuggets|ConTest|DecTest|McDiv) ")
TASK_RE = re.compile(r"^\s{2}(\S[^\s].*?)\s{2,}(\S+)\s+\((\w+)\)\s+([+\-]\d+\.\d+|nan)\s+(\S+)\s+(\S+)\s*$")
CONT_RE = re.compile(r"^\s{30,}(\S+)\s+\((\w+)\)\s+([+\-]\d+\.\d+|nan)\s+(\S+)\s+(\S+)\s*$")


def parse(path: Path) -> dict:
    """Return {(section, task, metric, unit): (rho, auc_or_dash, oca_or_dash)}."""
    out: dict = {}
    section = None
    cur_task = None
    for line in path.read_text().splitlines():
        m_sec = SECTION_RE.match(line)
        if m_sec:
            section = m_sec.group(1)
            cur_task = None
            continue
        m_task = TASK_RE.match(line)
        if m_task:
            cur_task = m_task.group(1).strip()
            metric, unit, rho, auc, oca = m_task.group(2), m_task.group(3), m_task.group(4), m_task.group(5), m_task.group(6)
            out[(section, cur_task, metric, unit)] = (rho, auc, oca)
            continue
        m_cont = CONT_RE.match(line)
        if m_cont and cur_task is not None:
            metric, unit, rho, auc, oca = m_cont.group(1), m_cont.group(2), m_cont.group(3), m_cont.group(4), m_cont.group(5)
            out[(section, cur_task, metric, unit)] = (rho, auc, oca)
    return out


def _fmt_signed(x_str: str) -> str:
    """Format a value that may be 'nan', '—', or a number; preserve sign."""
    if x_str in ("—", "nan", "?"):
        return "---"
    try:
        v = float(x_str)
        return f"{v:+.3f}" if v < 0 else f"{v:.3f}"
    except ValueError:
        return "---"


def _fmt_unsigned(x_str: str) -> str:
    if x_str in ("—", "nan", "?"):
        return "---"
    try:
        return f"{float(x_str):.3f}"
    except ValueError:
        return "---"


# Sections to include in the latex table, with ordering and display name.
# Skip ConTest because the paper's main text already shows ConTest in detail;
# the appendix focuses on McDiv (binary, where humans labeled), McDiv_nuggets
# (binary content nuggets), and DecTest (continuous temperature).
LATEX_SECTIONS = [
    ("McDiv", "McDiv"),
    ("McDiv_nuggets", "McDiv\\_nuggets"),
    ("ConTest", "ConTest"),
    ("DecTest", "DecTest"),
]


def emit_latex(q3: dict, qN: dict) -> None:
    """Write a side-by-side latex tabular body to LATEX_OUT_PATH."""
    LATEX_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    metric, unit = "C×a_n", "pb"

    lines: list[str] = []
    lines.append("% Generated by: scripts/compare_qwen_models.py --emit-latex")
    lines.append(
        "% Data sources: figures/tevet_validation/c_ainf_analysis_v3/summary_table.txt"
    )
    lines.append(
        "%               figures/tevet_validation/c_ainf_analysis_qwen3/summary_table.txt"
    )
    lines.append(
        "% Metric: C x a_n (per-byte). Q2.5-3B = Qwen2.5-3B local; Q3-30B = Qwen3-30B-A3B-Base via Tinker."
    )
    lines.append(r"\begin{tabular}{@{}llrrrrr@{}}")
    lines.append(r"\toprule")
    lines.append(
        r" &  & \multicolumn{2}{c}{Qwen2.5-3B} & \multicolumn{2}{c}{Qwen3-30B-A3B} & \\"
    )
    lines.append(r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}")
    lines.append(r"Section & Task & $\rho$ & AUC & $\rho$ & AUC & $\Delta$AUC \\")
    lines.append(r"\midrule")

    section_groups: dict[str, list[tuple[str, tuple, tuple]]] = {}
    for k in sorted(q3.keys()):
        sec, task, m, u = k
        if m != metric or u != unit:
            continue
        section_groups.setdefault(sec, []).append((task, q3[k], qN.get(k, ("?", "?", "?"))))

    first_section = True
    for sec_key, sec_display in LATEX_SECTIONS:
        if sec_key not in section_groups:
            continue
        if not first_section:
            lines.append(r"\midrule")
        first_section = False
        rows = section_groups[sec_key]
        for i, (task, v3, vN) in enumerate(rows):
            sec_cell = sec_display if i == 0 else ""
            task_disp = task.replace("_", "\\_")
            rho3 = _fmt_signed(v3[0])
            auc3 = _fmt_unsigned(v3[1])
            rhoN = _fmt_signed(vN[0])
            aucN = _fmt_unsigned(vN[1])
            try:
                d = float(vN[1]) - float(v3[1])
                d_str = f"{d:+.3f}"
            except ValueError:
                d_str = "---"
            lines.append(
                f"{sec_cell} & {task_disp} & {rho3} & {auc3} & {rhoN} & {aucN} & {d_str} \\\\"
            )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    LATEX_OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"\nSaved: {LATEX_OUT_PATH}")


def print_console(q3: dict, qN: dict) -> None:
    metric, unit = "C×a_n", "pb"
    last_section = None
    print(f"\n{'Section':<14} {'Task':<28} {'Q2.5-3B':<28} {'Q3-30B-A3B':<28} {'Δ AUC':<10}")
    print("-" * 110)
    for k in sorted(q3.keys()):
        sec, task, m, u = k
        if m != metric or u != unit:
            continue
        if sec != last_section:
            print()
            last_section = sec
        v3 = q3[k]
        vN = qN.get(k, ("?", "?", "?"))
        try:
            d_auc = float(vN[1]) - float(v3[1])
            d_str = f"{d_auc:+.3f}"
        except ValueError:
            d_str = "—"
        v3_str = f"ρ={v3[0]} AUC={v3[1]}"
        vN_str = f"ρ={vN[0]} AUC={vN[1]}"
        print(f"{sec:<14} {task:<28} {v3_str:<28} {vN_str:<28} {d_str:<10}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare Qwen2.5-3B vs Qwen3-30B-A3B Tevet results.")
    parser.add_argument("--emit-latex", action="store_true", help="Write latex tabular body for paper appendix.")
    args = parser.parse_args()

    q3 = parse(Q3_PATH)
    qN = parse(QN_PATH)
    print_console(q3, qN)
    if args.emit_latex:
        emit_latex(q3, qN)


if __name__ == "__main__":
    main()
