"""Compare per-task results between Qwen2.5-3B and Qwen3-30B-A3B-Base on Tevet.

Reads the two summary_table.txt files generated by analyze_c_ainf.py and prints
a side-by-side comparison for the C×a_n (pb) metric across all tasks/sections.

Usage:
    uv run python scripts/compare_qwen_models.py
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
Q3_PATH = PROJECT_ROOT / "figures/tevet_validation/c_ainf_analysis_v3/summary_table.txt"
QN_PATH = PROJECT_ROOT / "figures/tevet_validation/c_ainf_analysis_qwen3/summary_table.txt"

SECTION_RE = re.compile(r"^\s+(McDiv_nuggets|ConTest|DecTest|McDiv) ")
TASK_RE = re.compile(r"^\s{2}(\S[^\s].*?)\s{2,}(\S+)\s+\((\w+)\)\s+([+\-]\d+\.\d+|nan)\s+(\S+)\s+(\S+)\s*$")
CONT_RE = re.compile(r"^\s{30,}(\S+)\s+\((\w+)\)\s+([+\-]\d+\.\d+|nan)\s+(\S+)\s+(\S+)\s*$")


def parse(path: Path) -> dict:
    """Return {(section, task, metric, unit): (rho, auc_or_dash, oca_or_dash)}."""
    out: dict = {}
    section = None
    cur_task = None
    for line in path.read_text().splitlines():
        m_sec = SECTION_RE.match(line)
        if m_sec:
            section = m_sec.group(1)
            cur_task = None
            continue
        m_task = TASK_RE.match(line)
        if m_task:
            cur_task = m_task.group(1).strip()
            metric, unit, rho, auc, oca = m_task.group(2), m_task.group(3), m_task.group(4), m_task.group(5), m_task.group(6)
            out[(section, cur_task, metric, unit)] = (rho, auc, oca)
            continue
        m_cont = CONT_RE.match(line)
        if m_cont and cur_task is not None:
            metric, unit, rho, auc, oca = m_cont.group(1), m_cont.group(2), m_cont.group(3), m_cont.group(4), m_cont.group(5)
            out[(section, cur_task, metric, unit)] = (rho, auc, oca)
    return out


def main() -> None:
    q3 = parse(Q3_PATH)
    qN = parse(QN_PATH)

    metric, unit = "C×a_n", "pb"

    last_section = None
    print(f"\n{'Section':<14} {'Task':<28} {'Q2.5-3B':<28} {'Q3-30B-A3B':<28} {'Δ AUC':<10}")
    print("-" * 110)
    for k in sorted(q3.keys()):
        sec, task, m, u = k
        if m != metric or u != unit:
            continue
        if sec != last_section:
            print()
            last_section = sec
        v3 = q3[k]
        vN = qN.get(k, ("?", "?", "?"))
        try:
            d_auc = float(vN[1]) - float(v3[1])
            d_str = f"{d_auc:+.3f}"
        except ValueError:
            d_str = "—"
        v3_str = f"ρ={v3[0]} AUC={v3[1]}"
        vN_str = f"ρ={vN[0]} AUC={vN[1]}"
        print(f"{sec:<14} {task:<28} {v3_str:<28} {vN_str:<28} {d_str:<10}")


if __name__ == "__main__":
    main()
