"""Generate the mode count scaling table for the paper appendix.

Reads results/mode_count/qwen2.5-3b_1k_draws.json and
results/mode_count/qwen2.5-3b_fits.json, computes per-m statistics,
and writes results/tables/mode_count_scaling.tex (tabular body only).

Usage:
    uv run python scripts/generate_mode_count_table.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DRAWS_PATH = PROJECT_ROOT / "results/mode_count/qwen2.5-3b_1k_draws.json"
FITS_PATH = PROJECT_ROOT / "results/mode_count/qwen2.5-3b_fits.json"
OUT_PATH = PROJECT_ROOT / "results/tables/mode_count_scaling.tex"


def main() -> None:
    draws = json.load(open(DRAWS_PATH))
    fits_list = json.load(open(FITS_PATH))

    # Group runs by m
    runs_by_m: dict[int, list[dict]] = {}
    for run in draws["runs"]:
        runs_by_m.setdefault(run["m"], []).append(run)

    # Group fits by m (fits is a list, not a dict)
    fits_by_m: dict[int, dict] = {}
    for entry in fits_list:
        fits_by_m[entry["m"]] = entry

    mode_counts = sorted(runs_by_m.keys())

    lines: list[str] = []
    lines.append(f"% Generated by: scripts/generate_mode_count_table.py")
    lines.append(f"% Data source: results/mode_count/qwen2.5-3b_1k_draws.json")
    lines.append(f"%              results/mode_count/qwen2.5-3b_fits.json")
    lines.append(r"\begin{tabular}{@{}r rrrr@{}}")
    lines.append(r"\toprule")
    lines.append(
        r"$m$ & $E_{\mathrm{fit}}$ (bits) & $a_n$ (bits) & $\sigma_\ell$ (bits/byte) & $k_0$ \\"
    )
    lines.append(r"\midrule")

    for m in mode_counts:
        runs = runs_by_m[m]
        fit = fits_by_m.get(m)

        # a_n: last point of a_k_curve (total bits)
        a_n_vals = [run["a_k_curve"][-1] for run in runs]
        a_n_mean = np.mean(a_n_vals)

        # sigma_ell: coherence spread
        sigma_vals = [run["coherence_spread_sigma"] for run in runs]
        sigma_mean = np.mean(sigma_vals)

        # E_fit and k_0 from fits
        if fit is not None:
            e_fit_mean = fit["E_fit"]
            e_fit_lo = fit.get("E_fit_boot_ci_lo", e_fit_mean)
            e_fit_hi = fit.get("E_fit_boot_ci_hi", e_fit_mean)
            e_fit_half = (e_fit_hi - e_fit_lo) / 2
            k0_mean = fit["k0"]
        else:
            e_fit_mean = float("nan")
            e_fit_half = float("nan")
            k0_mean = float("nan")

        e_fit_str = f"${int(round(e_fit_mean))} \\pm {int(round(e_fit_half))}$"
        a_n_str = f"{a_n_mean:.1f}"
        sigma_str = f"{sigma_mean:.1f}"
        k0_str = f"${k0_mean:.1f}$"

        lines.append(f"{m}  & {e_fit_str} & {a_n_str} & {sigma_str} & {k0_str} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Saved: {OUT_PATH}")


if __name__ == "__main__":
    main()
