"""Generate the scenario validation table for the paper.

Reads results/scenario_metrics_v3_gpt2_100perm.json (GPT-2) and
results/scenario_metrics_v3_qwen3b_100perm.json (Qwen2.5-3B),
computes mean across 5 prompts for each scenario,
and writes results/tables/scenario_validation.tex (tabular body only).

Usage:
    uv run python scripts/generate_scenario_table.py
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GPT2_PATH = PROJECT_ROOT / "results/scenario_metrics_v3_gpt2_100perm.json"
QWEN_PATH = PROJECT_ROOT / "results/scenario_metrics_v3_qwen3b_100perm.json"
QWEN_MODEL_LABEL = "Qwen2.5-3B"
OUT_PATH = PROJECT_ROOT / "results/tables/scenario_validation.tex"

SCENARIO_ORDER = ["pure_noise", "multi_incoherent", "multi_mode", "one_mode", "mixed"]
SCENARIO_NAMES = {
    "pure_noise": "Pure noise",
    "multi_incoherent": "Multi-incoher.",
    "multi_mode": "Multi-mode",
    "one_mode": "One-mode",
    "mixed": "Mixed",
}


def extract_metrics(data: dict) -> dict[str, list[dict]]:
    """Return {scenario_name: [per-prompt dicts]}."""
    return data["scenarios"]


def fmt(val: float) -> str:
    if abs(val) < 0.01:
        return f"{val:.3f}"
    return f"{val:.2f}" if abs(val) < 10 else f"{val:.1f}"


def main() -> None:
    gpt2 = json.load(open(GPT2_PATH))
    qwen = json.load(open(QWEN_PATH))

    lines: list[str] = []
    lines.append("% Generated by: scripts/generate_scenario_table.py")
    lines.append(f"% Data sources: {GPT2_PATH.relative_to(PROJECT_ROOT)}")
    lines.append(f"%               {QWEN_PATH.relative_to(PROJECT_ROOT)}")
    lines.append(r"\begin{tabular}{@{}l rrrrrrr rrrrrrr@{}}")
    lines.append(r"\toprule")
    lines.append(
        r"& \multicolumn{7}{c}{\textbf{GPT-2 (124M)}} & \multicolumn{7}{c}{\textbf{"
        + QWEN_MODEL_LABEL
        + r"}} \\"
    )
    lines.append(r"\cmidrule(lr){2-8} \cmidrule(lr){9-15}")
    lines.append(
        r"Scenario & $a_1$ & $a_n$ & $C$ & $\mathbf{D_{Ca_n}}$ & $E$ & $C\!\times\!E$ & $\sigma_\ell$ "
        r"& $a_1$ & $a_n$ & $C$ & $\mathbf{D_{Ca_n}}$ & $E$ & $C\!\times\!E$ & $\sigma_\ell$ \\"
    )
    lines.append(r"\midrule")

    for scenario in SCENARIO_ORDER:
        name = SCENARIO_NAMES[scenario]
        cells = [name]

        for data in [gpt2, qwen]:
            prompts = data["scenarios"][scenario]
            # a_1 per-byte: first element of a_k_curve_per_byte
            a1_vals = [p["a_k_curve_per_byte"][0] for p in prompts]
            # a_n per-byte: last element of a_k_curve_per_byte
            an_vals = [p["a_k_curve_per_byte"][-1] for p in prompts]
            cs = [p["coherence_C"] for p in prompts]
            # D_{a_inf} = C * a_n (per-byte)
            d_ainf = [c * a for c, a in zip(cs, an_vals)]
            # E_rate (per-byte excess entropy)
            e_rates = [p["excess_entropy_E_rate"] for p in prompts]
            # C x E_rate (per-byte). Note: `diversity_score_D` in the JSON is
            # `C * excess_entropy_E` (total bits); `diversity_score_D_rate` is
            # the per-byte form, which is what this table reports.
            ds = [p["diversity_score_D_rate"] for p in prompts]
            sigmas = [p["coherence_spread_sigma"] for p in prompts]

            d_ainf_str = r"\textbf{" + fmt(np.mean(d_ainf)) + "}"
            cells.append(fmt(np.mean(a1_vals)))
            cells.append(fmt(np.mean(an_vals)))
            cells.append(fmt(np.mean(cs)))
            cells.append(d_ainf_str)
            cells.append(fmt(np.mean(e_rates)))
            cells.append(fmt(np.mean(ds)))
            cells.append(fmt(np.mean(sigmas)))

        # Handle negative sign for mixed scenario
        row = " & ".join(cells) + r" \\"
        # Replace minus signs with $-$ for proper typesetting
        row = row.replace("-0.", "$-$0.")
        row = row.replace("-1.", "$-$1.")
        lines.append(row)

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Saved: {OUT_PATH}")


if __name__ == "__main__":
    main()
