# /// script
# dependencies = ["dash>=2.14", "plotly>=5.18", "numpy>=1.24"]
# ///
"""Interactive scatter plot for auditing C×a_n diversity metric results.

Dash app that lets you click on individual data points to inspect:
- The sample's a_k curve (per-byte, with per-permutation curves)
- Summary statistics (E, C, σ_ℓ, a_n, etc.)
- Full response text

Requires SSH port forwarding to view on a remote machine:
    ssh -L 8050:localhost:8050 user@server
    # On server: uv run scripts/interactive_scatter.py --run-tag qwen25_completion_v3
    # On laptop: open http://localhost:8050

Data provenance:
- Sidecar JSONs: results/tevet/{run_tag}/*/*.icl_curves.{run_tag}.json
- CSVs: results/tevet/{run_tag}/*/*.csv
- Generated by: scripts/compute_icl_metrics_for_tevet.py

Usage:
    uv run scripts/interactive_scatter.py --run-tag qwen25_completion_v3
    uv run scripts/interactive_scatter.py --run-tag qwen25_completion_v3 --port 8051
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
from dash import Dash, Input, Output, callback, dcc, html
from plotly.subplots import make_subplots

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESULTS_BASE = PROJECT_ROOT / "results" / "tevet"


# ---------------------------------------------------------------------------
# Data loading (same patterns as analyze_c_ainf.py)
# ---------------------------------------------------------------------------

def load_sidecar(sidecar_path: Path) -> dict[str, dict]:
    with open(sidecar_path) as f:
        data = json.load(f)
    return {k: v for k, v in data.items() if not k.startswith("__")}


def load_csv_rows(csv_path: Path) -> dict[str, dict]:
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    key_col = "sidecar_key" if rows and "sidecar_key" in rows[0] else "sample_id"
    return {row[key_col]: row for row in rows}


def compute_per_byte_curve(entry: dict) -> list[float] | None:
    perm_curves = entry.get("per_permutation_a_k_curves")
    perm_bytes = entry.get("per_permutation_byte_counts")
    if perm_curves is None or perm_bytes is None:
        return entry.get("a_k_curve_per_byte")
    per_byte_curve: list[float] = []
    for k_idx in range(len(perm_curves[0])):
        ratios = []
        for p in range(len(perm_curves)):
            bits = perm_curves[p][k_idx]
            bc = perm_bytes[p][k_idx]
            if bc > 0:
                ratios.append(bits / bc)
        per_byte_curve.append(sum(ratios) / len(ratios) if ratios else 0.0)
    return per_byte_curve


# ---------------------------------------------------------------------------
# Load all data into a flat list of sample dicts
# ---------------------------------------------------------------------------

def load_all_samples(
    data_dir: Path, tag: str,
) -> list[dict]:
    """Load all samples with metrics, curves, and response text."""
    all_samples: list[dict] = []

    for sidecar_path in sorted(data_dir.rglob(f"*.icl_curves.{tag}.json")):
        csv_stem = sidecar_path.name.replace(f".icl_curves.{tag}.json", "")
        csv_path = sidecar_path.with_name(csv_stem + ".csv")
        if not csv_path.exists():
            continue

        dataset_key = f"{sidecar_path.parent.name}/{csv_stem}"
        sidecar = load_sidecar(sidecar_path)
        csv_rows = load_csv_rows(csv_path)

        resp_cols = sorted(
            [c for c in next(iter(csv_rows.values())) if c.startswith("resp_")]
        )

        for sid, entry in sidecar.items():
            row = csv_rows.get(sid)
            if row is None:
                continue

            label = float(row.get("label_value", "nan"))
            if np.isnan(label):
                continue

            metrics = entry.get("metrics", {})
            C = metrics.get("coherence_C", 0.0)
            a_k_pb = compute_per_byte_curve(entry)
            a_k_bits = entry.get("a_k_curve", [])

            if not a_k_pb or len(a_k_pb) < 2:
                continue

            a_n_pb = a_k_pb[-1]
            C_a_n_pb = C * a_n_pb

            responses = [row.get(c, "") for c in resp_cols]
            context = row.get("context", "")

            all_samples.append({
                "sidecar_key": sid,
                "dataset": dataset_key,
                "label": label,
                "context": context,
                "responses": responses,
                # Metrics
                "C": C,
                "a_n_pb": a_n_pb,
                "C_a_n_pb": C_a_n_pb,
                "E": metrics.get("excess_entropy_E", 0.0),
                "E_rate": metrics.get("excess_entropy_E_rate", 0.0),
                "D": metrics.get("diversity_score_D", 0.0),
                "sigma": metrics.get("coherence_spread_sigma", 0.0),
                "mean_byte_length": metrics.get("mean_byte_length", 0.0),
                # Curves
                "a_k_pb": a_k_pb,
                "a_k_bits": a_k_bits,
                "per_perm_curves": entry.get("per_permutation_a_k_curves"),
                "per_perm_bytes": entry.get("per_permutation_byte_counts"),
                "uncond_pb": entry.get("unconditional_surprises", []),
                "uncond_bits": entry.get("unconditional_total_bits", []),
            })

    return all_samples


# ---------------------------------------------------------------------------
# Build the Dash app
# ---------------------------------------------------------------------------

def build_app(all_samples: list[dict], run_tag: str) -> Dash:
    # Group by dataset, filter to binary with_hds datasets for the main scatter
    datasets: dict[str, list[dict]] = {}
    for s in all_samples:
        datasets.setdefault(s["dataset"], []).append(s)

    # Filter to binary datasets with enough samples
    binary_datasets = {
        k: v for k, v in sorted(datasets.items())
        if len(set(s["label"] for s in v)) == 2 and len(v) >= 20
    }

    dataset_names = list(binary_datasets.keys())

    app = Dash(__name__)

    app.layout = html.Div(
        style={"fontFamily": "monospace", "maxWidth": "1400px", "margin": "0 auto",
               "padding": "20px"},
        children=[
            html.H2(f"ICL Diversity Audit — {run_tag}"),
            html.P("Click a point to inspect. Hover for summary."),

            # Dataset selector
            html.Label("Dataset:"),
            dcc.Dropdown(
                id="dataset-dropdown",
                options=[{"label": n, "value": n} for n in dataset_names],
                value=dataset_names[0] if dataset_names else None,
                style={"width": "500px", "marginBottom": "10px"},
            ),

            # Metric selector for Y axis
            html.Label("Y axis:"),
            dcc.Dropdown(
                id="metric-dropdown",
                options=[
                    {"label": "C × a_n (pb)", "value": "C_a_n_pb"},
                    {"label": "a_n (pb)", "value": "a_n_pb"},
                    {"label": "C (coherence)", "value": "C"},
                    {"label": "E (excess entropy)", "value": "E"},
                    {"label": "σ_ℓ (coherence spread)", "value": "sigma"},
                ],
                value="C_a_n_pb",
                style={"width": "300px", "marginBottom": "20px"},
            ),

            # Main scatter plot
            dcc.Graph(id="scatter-plot", style={"height": "500px"}),

            # Detail panel (updates on click)
            html.Hr(),
            html.H3(id="detail-title", children="Click a point to inspect"),
            html.Div(id="detail-panel", style={"display": "flex", "gap": "30px"}, children=[
                # Left: a_k curve
                html.Div(style={"flex": "1"}, children=[
                    dcc.Graph(id="ak-curve-plot", style={"height": "350px"}),
                ]),
                # Right: metrics + text
                html.Div(style={"flex": "1.5", "overflowY": "auto", "maxHeight": "600px"}, children=[
                    html.Pre(id="metrics-text",
                             style={"fontSize": "13px", "whiteSpace": "pre-wrap"}),
                    html.Hr(),
                    html.H4("Responses"),
                    html.Pre(id="responses-text",
                             style={"fontSize": "12px", "whiteSpace": "pre-wrap",
                                    "maxHeight": "400px", "overflowY": "auto",
                                    "backgroundColor": "#f5f5f5", "padding": "10px"}),
                ]),
            ]),

            # Hidden store for full sample data (JSON)
            dcc.Store(id="samples-store"),
        ],
    )

    # Store sample data as JSON for client-side access
    @app.callback(
        Output("samples-store", "data"),
        Input("dataset-dropdown", "value"),
    )
    def update_store(dataset_name: str | None) -> list[dict] | None:
        if dataset_name is None:
            return None
        samples = binary_datasets.get(dataset_name, [])
        # Serialize — include everything needed for detail panel
        return [
            {
                "idx": i,
                "sidecar_key": s["sidecar_key"],
                "label": s["label"],
                "context": s["context"],
                "responses": s["responses"],
                "C": s["C"],
                "a_n_pb": s["a_n_pb"],
                "C_a_n_pb": s["C_a_n_pb"],
                "E": s["E"],
                "E_rate": s["E_rate"],
                "D": s["D"],
                "sigma": s["sigma"],
                "mean_byte_length": s["mean_byte_length"],
                "a_k_pb": s["a_k_pb"],
                "a_k_bits": s["a_k_bits"],
                "uncond_pb": s["uncond_pb"],
                "uncond_bits": s["uncond_bits"],
            }
            for i, s in enumerate(samples)
        ]

    @app.callback(
        Output("scatter-plot", "figure"),
        Input("samples-store", "data"),
        Input("metric-dropdown", "value"),
    )
    def update_scatter(
        samples_data: list[dict] | None, metric_key: str,
    ) -> go.Figure:
        if not samples_data:
            return go.Figure()

        fig = go.Figure()
        for label_val, name, color in [
            (0.0, "Low diversity", "rgba(31,119,180,0.5)"),
            (1.0, "High diversity", "rgba(214,39,40,0.5)"),
        ]:
            group = [s for s in samples_data if s["label"] == label_val]
            if not group:
                continue

            rng = np.random.default_rng(42)
            jitter = rng.uniform(-0.15, 0.15, len(group))
            x = [label_val + j for j in jitter]
            y = [s[metric_key] for s in group]
            custom = [s["idx"] for s in group]

            hover_texts = []
            for s in group:
                resp_preview = " | ".join(
                    r[:40] + "..." if len(r) > 40 else r for r in s["responses"]
                )
                hover_texts.append(
                    f"<b>{s['sidecar_key']}</b><br>"
                    f"C={s['C']:.4f}, a_n={s['a_n_pb']:.3f}, "
                    f"C×a_n={s['C_a_n_pb']:.3f}<br>"
                    f"E={s['E']:.1f}, σ={s['sigma']:.3f}<br>"
                    f"{resp_preview[:200]}"
                )

            fig.add_trace(go.Scatter(
                x=x, y=y,
                mode="markers",
                marker=dict(size=8, color=color, line=dict(width=0.5, color="white")),
                name=name,
                customdata=custom,
                hovertext=hover_texts,
                hoverinfo="text",
            ))

        fig.update_layout(
            xaxis=dict(
                tickvals=[0, 1],
                ticktext=["Low div", "High div"],
                range=[-0.4, 1.4],
            ),
            yaxis_title=metric_key,
            hovermode="closest",
            margin=dict(l=60, r=20, t=40, b=40),
        )
        return fig

    @app.callback(
        Output("detail-title", "children"),
        Output("metrics-text", "children"),
        Output("responses-text", "children"),
        Output("ak-curve-plot", "figure"),
        Input("scatter-plot", "clickData"),
        Input("samples-store", "data"),
    )
    def update_detail(
        click_data: dict | None,
        samples_data: list[dict] | None,
    ) -> tuple[str, str, str, go.Figure]:
        if click_data is None or not samples_data:
            return (
                "Click a point to inspect",
                "",
                "",
                go.Figure(),
            )

        pt = click_data["points"][0]
        idx = pt.get("customdata")
        if idx is None:
            return ("No data for this point", "", "", go.Figure())

        s = samples_data[idx]

        # Title
        label_name = "HIGH diversity" if s["label"] == 1.0 else "LOW diversity"
        title = f"{s['sidecar_key']} — {label_name}"

        # Metrics text
        metrics_lines = [
            f"C (coherence)      = {s['C']:.4f}",
            f"a_n (pb)           = {s['a_n_pb']:.4f}",
            f"C × a_n (pb)       = {s['C_a_n_pb']:.4f}",
            f"E (excess entropy) = {s['E']:.2f} bits",
            f"E_rate             = {s['E_rate']:.4f} bits/byte",
            f"D (C × E)          = {s['D']:.2f} bits",
            f"σ_ℓ (coh. spread)  = {s['sigma']:.4f}",
            f"mean byte length   = {s['mean_byte_length']:.1f}",
            "",
            f"Context: \"{s['context']}\"",
        ]

        # Unconditional surprises
        if s.get("uncond_pb"):
            metrics_lines.append("")
            metrics_lines.append("Unconditional surprise (pb) per response:")
            for i, u in enumerate(s["uncond_pb"]):
                metrics_lines.append(f"  resp_{i}: {u:.4f} bits/byte")

        metrics_text = "\n".join(metrics_lines)

        # Response text
        resp_lines = []
        for i, r in enumerate(s["responses"]):
            resp_lines.append(f"--- Response {i} ---")
            resp_lines.append(r)
            resp_lines.append("")
        responses_text = "\n".join(resp_lines)

        # a_k curve plot
        a_k_pb = s["a_k_pb"]
        a_k_bits = s["a_k_bits"]
        k = list(range(1, len(a_k_pb) + 1))

        fig = make_subplots(rows=1, cols=2, subplot_titles=["a_k (bits/byte)", "a_k (total bits)"])

        fig.add_trace(
            go.Scatter(x=k, y=a_k_pb, mode="lines+markers", name="mean (pb)",
                       marker=dict(size=8, color="red"), line=dict(width=2)),
            row=1, col=1,
        )
        fig.add_trace(
            go.Scatter(x=k, y=a_k_bits, mode="lines+markers", name="mean (bits)",
                       marker=dict(size=8, color="blue"), line=dict(width=2)),
            row=1, col=2,
        )

        fig.update_xaxes(title_text="k", dtick=1, row=1, col=1)
        fig.update_xaxes(title_text="k", dtick=1, row=1, col=2)
        fig.update_yaxes(title_text="bits/byte", row=1, col=1)
        fig.update_yaxes(title_text="bits", row=1, col=2)
        fig.update_layout(
            margin=dict(l=50, r=20, t=40, b=40),
            showlegend=False,
        )

        return title, metrics_text, responses_text, fig

    return app


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Interactive scatter for auditing diversity metrics")
    parser.add_argument("--run-tag", type=str, default="qwen25_completion_v3")
    parser.add_argument("--port", type=int, default=8050)
    args = parser.parse_args()

    data_dir = RESULTS_BASE / args.run_tag
    if not data_dir.exists():
        print(f"No data at {data_dir}")
        sys.exit(1)

    print(f"Loading data from {data_dir}...")
    all_samples = load_all_samples(data_dir, args.run_tag)
    print(f"Loaded {len(all_samples)} samples")

    app = build_app(all_samples, args.run_tag)

    print(f"\nStarting Dash app on http://0.0.0.0:{args.port}")
    print(f"Open http://localhost:{args.port} in your laptop browser")
    print("(requires SSH port forwarding: ssh -L {0}:localhost:{0} ...)".format(args.port))
    app.run(host="0.0.0.0", port=args.port, debug=False)


if __name__ == "__main__":
    main()
